export const page = `<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>QQQShare</title><style>
:root{font-family:Inter,system-ui,sans-serif;color:#172036;background:#f4f7fb}*{box-sizing:border-box}body{margin:0;padding:24px}.app{max-width:760px;margin:auto}.top,.address,.share-tools,.settings,.file{display:flex;align-items:center;gap:12px}.top,.address,.settings{justify-content:space-between}.brand{font-weight:850;font-size:28px}.intro-card{margin-top:18px;padding:20px 22px;border-radius:18px;background:white;border:1px solid #e4e9f2}.intro-card strong{display:block;font-size:18px;margin-bottom:7px}.intro-card p{margin:0;color:#68738b;line-height:1.55}.share-card{margin-top:12px;padding:22px 24px;border-radius:18px;background:#172036;color:white;box-shadow:0 10px 28px #24345b24}.share-label{font-size:13px;color:#b9c5df;margin-bottom:8px}.address code{color:white;font-weight:750;font-size:clamp(20px,4.5vw,31px);letter-spacing:-.5px;overflow:hidden;text-overflow:ellipsis}.share-tools{margin-top:16px}.qr{width:112px;height:112px;background:white;padding:6px;border-radius:12px}.copy{flex:none;background:#5965e8;color:white;font-weight:700}.danger{background:#d94b61}.pill{background:#dff7ea;color:#147343;padding:7px 11px;border-radius:99px;font-size:13px;white-space:nowrap}.drop{margin:18px 0 24px;padding:50px 20px;text-align:center;border:2px dashed #91a4c7;border-radius:20px;background:white;cursor:pointer}.drop.over{border-color:#5965e8;background:#f0f1ff}.drop strong{display:block;font-size:20px;margin-bottom:8px}.settings,.file{background:white;border-radius:14px;padding:15px;margin:10px 0}.file .meta{min-width:0;flex:1}.name{font-weight:700;overflow:hidden;text-overflow:ellipsis}.sub{font-size:13px;color:#68738b;margin-top:5px}.timer{font-variant-numeric:tabular-nums;color:#5965e8}button,select,.download{border:0;border-radius:10px;padding:10px 13px;font:inherit}.download,button{background:#5965e8;color:white;cursor:pointer;text-decoration:none}select{background:#eef1f7}.empty{text-align:center;color:#7d879a;padding:30px}.owner-only[hidden]{display:none}@media(max-width:540px){body{padding:15px}.share-card{padding:18px}.address{align-items:stretch;flex-direction:column}.address code{font-size:22px}.settings{align-items:flex-start;flex-direction:column}.drop{padding:38px 15px}}
</style></head><body><main class="app"><div class="top"><div class="brand">QQQShare</div><span class="pill">LAN · 임시 공유</span></div><section class="intro-card"><strong>사람과 AI를 위한 만료형 아티팩트 교환</strong><p>같은 Wi-Fi에서 주소만 열어 안전하게 받고, 설정한 시간이 지나면 공유가 자동 종료됩니다.</p></section><section class="share-card"><div class="share-label">읽기 전용 공유 주소</div><div class="address"><code id="address">주소 확인 중…</code><button id="copy" class="copy" type="button">주소 복사</button></div><div class="share-tools owner-only" hidden><img id="qr" class="qr" alt="공유 주소 QR 코드"><button id="stop" class="danger" type="button">전체 공유 중지</button></div></section>
<section id="drop" class="drop owner-only" hidden><strong>파일을 여기에 놓으세요</strong><span>브라우저에서 선택하려면 클릭</span><input id="picker" type="file" multiple hidden></section>
<section class="settings owner-only" hidden><span>새 파일 공유 정책</span><div><select id="duration"><option value="1">1초</option><option value="10">10초</option><option value="30">30초</option><option value="60" selected>1분</option><option value="300">5분</option><option value="600">10분</option><option value="1800">30분</option><option value="3600">1시간</option><option value="21600">6시간</option><option value="86400">24시간</option></select> <label><input id="once" type="checkbox"> 1회 받은 뒤 폐기</label></div></section>
<div id="status" class="sub"></div><section id="files"></section></main><script>
const token=new URLSearchParams(location.search).get('t')||'';const drop=document.querySelector('#drop'),picker=document.querySelector('#picker'),files=document.querySelector('#files'),status=document.querySelector('#status'),duration=document.querySelector('#duration'),once=document.querySelector('#once'),address=document.querySelector('#address'),copy=document.querySelector('#copy'),stop=document.querySelector('#stop'),qr=document.querySelector('#qr');let shareUrl=location.href,role='reader';
const api=(path,options={})=>fetch('/api'+path+(path.includes('?')?'&':'?')+'t='+encodeURIComponent(token),options);
for(const eventName of ['dragover','drop']) document.addEventListener(eventName,event=>event.preventDefault());
async function loadInfo(){const r=await api('/info');if(!r.ok)return;const info=await r.json();role=info.role;shareUrl=info.urls[0]||location.href;const parsed=new URL(shareUrl);address.textContent=parsed.host+'/qqq';address.title=shareUrl;if(role==='owner'){document.querySelectorAll('.owner-only').forEach(x=>x.hidden=false);qr.src='/api/qr?t='+encodeURIComponent(token)}}
copy.onclick=async()=>{await navigator.clipboard.writeText(shareUrl);const old=copy.textContent;copy.textContent='복사됨';setTimeout(()=>copy.textContent=old,1200)};
drop.onclick=()=>picker.click();picker.onchange=()=>upload([...picker.files]);['dragenter','dragover'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.add('over')}));['dragleave','drop'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.remove('over')}));drop.addEventListener('drop',e=>upload([...e.dataTransfer.files]));
async function saveSettings(){await api('/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({duration:Number(duration.value),oneTime:once.checked})})}duration.onchange=saveSettings;once.onchange=saveSettings;
stop.onclick=async()=>{if(confirm('현재 공유를 모두 종료할까요?')){await api('/stop',{method:'POST'});document.body.innerHTML='<main class="app"><section class="intro-card"><strong>공유가 종료되었습니다.</strong></section></main>'}};
async function upload(items){for(const file of items){status.textContent='업로드 중: '+file.name;const r=await api('/upload?name='+encodeURIComponent(file.name),{method:'POST',body:file});if(!r.ok){status.textContent='업로드 실패: '+await r.text();return}}status.textContent='업로드 완료';await refresh()}
function remain(ms){const s=Math.max(0,Math.ceil(ms/1000));return s>=3600?Math.floor(s/3600)+'시간 '+Math.floor(s%3600/60)+'분':s>=60?Math.floor(s/60)+'분 '+s%60+'초':s+'초'}
async function refresh(){const r=await api('/files');if(!r.ok){files.innerHTML='<div class="empty">접근할 수 없는 공유입니다.</div>';return}const data=await r.json();duration.value=String(data.duration);once.checked=Boolean(data.oneTime);files.innerHTML=data.files.length?data.files.map(f=>'<article class="file"><div class="meta"><div class="name">'+escapeHtml(f.name)+'</div><div class="sub">'+formatBytes(f.size)+(f.oneTime?' · 1회용':'')+' · 다운로드 '+f.downloads+'회 · <span class="timer" data-until="'+f.expiresAt+'"></span></div></div><a class="download" href="/api/download/'+encodeURIComponent(f.id)+'?t='+encodeURIComponent(token)+'">받기</a>'+(role==='owner'?'<button class="danger" onclick="revokeFile(\''+f.id+'\')">폐기</button>':'')+'</article>').join(''):'<div class="empty">공유 중인 파일이 없습니다.</div>';tick()}
async function revokeFile(id){if(confirm('이 파일 공유를 즉시 종료할까요?')){await api('/files/'+encodeURIComponent(id),{method:'DELETE'});await refresh()}}
function tick(){document.querySelectorAll('[data-until]').forEach(x=>x.textContent=remain(Number(x.dataset.until)-Date.now())+' 남음')};function formatBytes(n){return n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB'}function escapeHtml(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}loadInfo();refresh();setInterval(()=>{tick();refresh()},3000);
</script></body></html>`;
